# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Source Incite
author:
  name: stevenseeley
  email: steven@srcincite.io
description: > # this means to ignore newlines until "baseurl:"
  experts in offensive technologies

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://srcincite.io" # the base hostname & protocol for your site
twitter_username: sourceincite
github_username:  sourceincite

minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: steventseeley
    github:  sourceincite
  
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
